### PR TITLE
ci: create a test directory to prevent dot file conflicts

### LINKED ISSUE #385: _.gitignore conflict causing CI to fail
`_.gitignore` is running into a conflict that needs to be manually overwritten.
This is causing CI to timeout waiting for command line feedback on how to resolve the conflict.

```
 conflict packages/generator-wcfactory/generators/start/templates/_.gitignore
? Overwrite packages/generator-wcfactory/generators/start/templates/_.gitignore?
 (ynaxdH) 
```

https://travis-ci.com/elmsln/wcfactory/jobs/174210814#L555

_Originally posted by @ChristianMurphy in https://github.com/elmsln/wcfactory/pull/381#issuecomment-459785731_

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolves #385

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Based off https://github.com/elmsln/wcfactory/issues/385#issuecomment-463046475
This should work, waiting for CI to confirm.

**Comment by ChristianMurphy** [comment]
That resolved it, thanks @ThatJoeMoore! :bow:

**Comment by ChristianMurphy** [comment]
There are still CI failures, the failures are due to an unrelated issue.
```
slim-test.umd.js → slim-test.umd.js...
[!] (commonjs plugin) SyntaxError: Export 'SlimTest' is not defined (84:9) in /home/travis/build/elmsln/wcf-test/factories/test/elements/slim-test/slim-test.umd.js
slim-test.umd.js (84:9)
82:   }
83: );
84: export { SlimTest };
             ^
SyntaxError: Export 'SlimTest' is not defined (84:9) in /home/travis/build/elmsln/wcf-test/factories/test/elements/slim-test/slim-test.umd.js
    at Object.pp$4.raise (/home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup/node_modules/acorn/src/location.js:15:13)
    at Object.pp$1.parseTopLevel (/home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup/node_modules/acorn/src/statement.js:27:12)
    at Object.parse (/home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup/node_modules/acorn/src/state.js:92:17)
    at Function.parse (/home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup/node_modules/acorn/src/state.js:112:37)
    at Graph.contextParse (/home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup/dist/rollup.js:17036:38)
    at tryParse (/home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup-plugin-commonjs/src/transform.js:34:10)
    at checkEsModule (/home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup-plugin-commonjs/src/transform.js:47:14)
    at /home/travis/build/elmsln/wcf-test/factories/test/node_modules/rollup-plugin-commonjs/src/index.js:104:52
    at <anonymous>
```

https://travis-ci.com/elmsln/wcfactory/jobs/177452048#L950-L968

**Comment by btopro** [comment]
oddd..

**Comment by btopro** [comment]
forcing a rerun to see if this fixes the Slim issue. Basically just reordered how it would build the element from template. I'm not using slim so I don't know if this works (and honestly could just take it out if it's not going to work w/ the way we've setup tooling since it global scopes some things anyway which is not the norm anymore)

**Comment by ChristianMurphy** [comment]
> forcing a rerun to see if this fixes the Slim issue. Basically just reordered how it would build the element from template

Looks to be working :tada: 
screenshot_2019-02-13 build 656 - elmsln wcfactory - travis ci

> it global scopes some things anyway which is not the norm anymore

Does it? Doesn't the build system create a wrapper around the code to prevent global scope leakage?

**Comment by btopro** [comment]
I misspoke. Slim was imported, the class was written directly into it so then it wouldn't be in scope of that page. Still was a scoping issue, glad to see it's resolved now

**Pull request merged**
