### PR TITLE
style: automatically format code

### PR DESCRIPTION
**Pull request by ChristianMurphy**
output from `yarn format`

followed by some manual fixes to suggestions from ESLint

### CODE REVIEW

**Comment by btopro** [comment]
sry I borked your merge w/ a refactor :)

**Comment by btopro** [comment]
ran yarn format so much of this should be redundant

**Comment by ChristianMurphy** [comment]
It could/should be, I'll close this in favor of a pre commit hook to autoformat

**Comment by btopro** [comment]
@ChristianMurphy https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/init/templates/package.json#L147-L151 is in the factories

**Pull request closed without merging**
