### PR TITLE
Move exports to bottom of the page.

### PR DESCRIPTION
**Pull request by cosmicdreams**

### CODE REVIEW

**Comment by cosmicdreams** [comment]
To fix: https://github.com/elmsln/wcfactory/issues/206

**Comment by btopro** [comment]
looks good for that one, can you fix this in the other element templates so we don't have them out of sync? They are largely identical so should just be moving it to bottom of all these

**Comment by cosmicdreams** [comment]
What other element templates?

**Comment by ChristianMurphy** [comment]
https://github.com/elmsln/wcfactory/blob/30d2896089cc0639a26a5b72e88a7903ce1434f8/packages/generator-wcfactory/generators/start/templates/templates/libraries/LitElement/LitElement.js#L7
https://github.com/elmsln/wcfactory/blob/16e1e894c498787b469245afa74d353d6d8555b3/packages/generator-wcfactory/generators/start/templates/templates/libraries/PolymerElement/PolymerElement.js#L7

**Pull request merged**
